import { useState } from "react";
import { ArrowRight, BookOpen, Check, ChevronDown, Code2, Github, Heart, Menu, MessageCircle, Network, Rocket, Shield, Terminal, X, Zap } from "lucide-react";

const routes = [
  { icon: BookOpen, label: "Brand new", detail: "Start with the basics", path: "wiki/First-Steps/", color: "lime" },
  { icon: Terminal, label: "Phone-only", detail: "Master EasyTether", path: "courses-and-guides/01-easytether-mastery/", color: "violet" },
  { icon: Code2, label: "Into music / ball / design / streaming", detail: "Pick a sandbox blueprint", path: "sandbox-blueprints/", color: "orange" },
  { icon: Rocket, label: "Ready to charge", detail: "Build a hustle", path: "hustle-index/ + PRICING.md", color: "cyan" },
  { icon: MessageCircle, label: "Just looking for brothers", detail: "Find the Spawn Zone", path: "Discussions → Spawn Zone", color: "pink" },
];

const repos = [
  { name: "fed-edu", description: "The main repo: manifesto, dashboard, courses, blueprints, wiki, everything.", status: "active", icon: Network },
  { name: "fed-comm-dm", description: "The custom DM system — spinning out when the block is ready.", status: "building", icon: MessageCircle },
  { name: "brother forks", description: "Your fork. Your name. Your ship. That's the whole point.", status: "yours", icon: Github },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  const copyCommand = async () => { try { await navigator.clipboard.writeText("git clone https://github.com/fedpromptly/fed-edu.git"); } catch { /* clipboard unavailable */ } setCopied(true); setTimeout(() => setCopied(false), 2200); };

  return (
    <main className="min-h-screen overflow-hidden bg-[#101312] text-[#f4f1e9]">
      <div className="pointer-events-none fixed inset-0 z-50 opacity-[0.045] grain" />
      <nav className="fixed left-0 right-0 top-0 z-40 flex items-center justify-between border-b border-white/10 bg-[#101312]/85 px-5 py-4 backdrop-blur-md md:px-10">
        <button onClick={() => scrollTo("top")} className="flex items-center gap-2 font-mono text-xs font-bold tracking-tight"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-[#b8f34a] text-[#101312]">F</span> FED-EDU</button>
        <div className="hidden items-center gap-8 font-mono text-[11px] text-[#aab2a8] md:flex"><button onClick={() => scrollTo("start")} className="hover:text-[#b8f34a]">Where to start</button><button onClick={() => scrollTo("rules")} className="hover:text-[#b8f34a]">Ground rules</button><button onClick={() => scrollTo("repos")} className="hover:text-[#b8f34a]">Repos</button><a href="https://github.com" target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2 text-white hover:border-[#b8f34a] hover:text-[#b8f34a]"><Github size={13} /> GitHub</a></div>
        <button aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)} className="rounded-md border border-white/15 p-2 md:hidden">{menuOpen ? <X size={16} /> : <Menu size={16} />}</button>
      </nav>
      {menuOpen && <div className="fixed inset-x-4 top-16 z-40 rounded-xl border border-white/10 bg-[#181d1b] p-5 shadow-2xl md:hidden"><div className="flex flex-col gap-5 font-mono text-sm"><button onClick={() => scrollTo("start")} className="text-left">Where to start</button><button onClick={() => scrollTo("rules")} className="text-left">Ground rules</button><button onClick={() => scrollTo("repos")} className="text-left">Repos</button></div></div>}

      <section id="top" className="relative border-b border-white/10 px-5 pb-20 pt-36 md:px-10 md:pb-28 md:pt-48 lg:px-20">
        <div className="absolute right-[-8%] top-20 h-[30rem] w-[30rem] rounded-full border border-[#b8f34a]/20 md:h-[42rem] md:w-[42rem]" /><div className="absolute right-[8%] top-44 h-3 w-3 rounded-full bg-[#b8f34a] shadow-[0_0_60px_25px_rgba(184,243,74,.28)]" />
        <div className="relative z-10 max-w-6xl"><div className="mb-7 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.2em] text-[#b8f34a]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#b8f34a]" /> org profile / online</div><h1 className="max-w-5xl font-display text-[clamp(4rem,11vw,10.5rem)] font-bold leading-[0.83] tracking-[-0.075em]">Welcome<br /><span className="text-[#b8f34a]">to the block.</span></h1><div className="mt-12 grid max-w-4xl gap-10 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-2xl text-lg leading-8 text-[#aab2a8] md:text-xl">The sovereign AI, coding & tech space for <strong className="text-white">all Black men.</strong> From first bike to second chance — every builder belongs here.</p><button onClick={() => scrollTo("start")} className="group flex w-fit items-center gap-3 rounded-full bg-[#b8f34a] px-6 py-3 font-mono text-xs font-bold text-[#101312] transition hover:bg-white"><span>Find your starting point</span><ArrowRight size={15} className="transition group-hover:translate-x-1" /></button></div></div>
        <div className="relative z-10 mt-20 flex flex-wrap gap-x-6 gap-y-3 border-t border-white/10 pt-5 font-mono text-[10px] uppercase tracking-[0.17em] text-[#69726c]"><span>Urban Dictionary + GitHub</span><span>×</span><span>FED-OS</span><span>×</span><span>fedpromptly</span></div>
      </section>

      <section id="manifesto" className="border-b border-white/10 bg-[#171c19] px-5 py-20 md:px-10 md:py-28 lg:px-20"><div className="grid gap-12 md:grid-cols-[0.35fr_1fr]"><div><span className="font-mono text-xs text-[#b8f34a]">01 / WHAT WE DO</span></div><div><h2 className="max-w-4xl font-display text-[clamp(2.8rem,6vw,6rem)] font-bold leading-[0.9] tracking-[-0.06em]">Tech is real-life<br /><span className="text-[#ff754d]">Minecraft.</span></h2><div className="mt-12 grid gap-8 text-[#aab2a8] md:grid-cols-2"><p className="max-w-md leading-7">We translate AI, coding, and tech into plain street terms so true beginners can grow naturally — build real projects, ship real products, and get paid without permission from any gatekeeper.</p><p className="max-w-md leading-7">Pick what you love. Build what you want. Don't ask if it's been done. We're doing it again with tech.</p></div></div></div></section>

      <section id="start" className="px-5 py-20 md:px-10 md:py-28 lg:px-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="font-mono text-xs text-[#b8f34a]">02 / WHERE TO START</span><h2 className="mt-5 font-display text-5xl font-bold tracking-[-0.06em] md:text-7xl">Choose your lane.</h2></div><p className="max-w-xs font-mono text-xs leading-5 text-[#69726c]">No wrong door. Every path gets you closer to shipping.</p></div><div className="mt-12 grid gap-3">{routes.map((route, index) => { const Icon = route.icon; return <button key={route.label} onClick={() => copyCommand()} className="group grid gap-4 border border-white/10 bg-[#171c19] p-5 text-left transition hover:-translate-y-0.5 hover:border-[#b8f34a]/50 hover:bg-[#1e261f] md:grid-cols-[2.6rem_1fr_auto] md:items-center"><span className="font-mono text-sm text-[#69726c]">0{index + 1}</span><span className="flex items-center gap-4"><span className={`flex h-11 w-11 items-center justify-center rounded-lg bg-${route.color}-500/10 text-[#b8f34a]`}><Icon size={20} /></span><span><strong className="block text-lg text-white">{route.label}</strong><span className="font-mono text-xs text-[#8e9990]">{route.detail}</span></span></span><span className="flex items-center justify-between gap-8 border-t border-white/10 pt-4 font-mono text-[10px] text-[#b8f34a] md:border-t-0 md:pt-0"><code>{route.path}</code><ArrowRight size={15} className="transition group-hover:translate-x-1" /></span></button>; })}</div><div className="mt-5 flex items-center gap-2 font-mono text-[10px] text-[#69726c]">{copied ? <><Check size={13} className="text-[#b8f34a]" /> path copied — now go build</> : <><Zap size={13} className="text-[#ff754d]" /> tap any lane to copy a starter command</>}</div></section>

      <section id="rules" className="border-y border-white/10 bg-[#b8f34a] px-5 py-20 text-[#101312] md:px-10 md:py-28 lg:px-20"><div className="grid gap-12 md:grid-cols-[0.65fr_1.35fr]"><div><span className="font-mono text-xs font-bold">03 / THE GROUND RULES</span><h2 className="mt-5 max-w-sm font-display text-5xl font-bold leading-[0.88] tracking-[-0.06em] md:text-7xl">Dap the attempt.</h2><p className="mt-8 max-w-sm font-mono text-xs leading-5 opacity-70">Full rules: CODE_OF_CONDUCT.md<br />How the block is run: GOVERNANCE.md</p></div><div className="grid gap-x-10 gap-y-8 md:grid-cols-2">{[{ icon: Heart, text: "No question is stupid — walk every brother through everything" }, { icon: MessageCircle, text: "No jargon without translation" }, { icon: Zap, text: "Celebrate the attempts — first push gets the same dap as first ship" }, { icon: Shield, text: "Zero tolerance for gatekeeping" }, { icon: Github, text: "Ownership stays with the builders" }, { icon: Heart, text: "Protect the younger brothers — no exceptions, no appeals" }].map(({ icon: Icon, text }) => <div key={text} className="flex gap-4 border-t border-[#101312]/20 pt-4"><Icon size={19} className="mt-1 shrink-0" /><p className="max-w-xs font-mono text-sm font-bold leading-6">{text}</p></div>)}</div></div></section>

      <section id="repos" className="px-5 py-20 md:px-10 md:py-28 lg:px-20"><div className="grid gap-12 md:grid-cols-[0.65fr_1.35fr]"><div><span className="font-mono text-xs text-[#b8f34a]">04 / THE REPOS</span><h2 className="mt-5 font-display text-5xl font-bold leading-[0.9] tracking-[-0.06em] md:text-7xl">Open source.<br /><span className="text-[#ff754d]">Open door.</span></h2></div><div className="grid gap-3">{repos.map(({ name, description, status, icon: Icon }) => <div key={name} className="flex items-start gap-4 border border-white/10 bg-[#171c19] p-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-white/5 text-[#b8f34a]"><Icon size={19} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-mono font-bold text-white">{name}</h3><span className="rounded-full border border-[#b8f34a]/30 px-2 py-1 font-mono text-[9px] uppercase tracking-widest text-[#b8f34a]">{status}</span></div><p className="mt-2 text-sm leading-6 text-[#8e9990]">{description}</p></div></div>)}</div></div></section>

      <section className="border-t border-white/10 bg-[#171c19] px-5 py-20 md:px-10 md:py-28 lg:px-20"><div className="relative overflow-hidden rounded-2xl border border-[#ff754d]/40 bg-[#241d1a] p-8 md:p-14"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border border-[#ff754d]/30" /><div className="relative z-10 max-w-3xl"><span className="font-mono text-xs text-[#ff754d]">05 / FUEL THE BLOCK</span><h2 className="mt-6 font-display text-5xl font-bold leading-[0.9] tracking-[-0.06em] md:text-7xl">Build the space<br /><span className="text-[#ff754d]">that builds us.</span></h2><p className="mt-8 max-w-xl text-lg leading-8 text-[#c0b5aa]">Every contribution buys refurbished desktops for raffles and data plans for brothers learning on tethered phones.</p><a href="https://ko-fi.com" target="_blank" rel="noreferrer" className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#ff754d] px-6 py-3 font-mono text-xs font-bold text-[#101312] hover:bg-white"><Heart size={15} /> Buy Me a Coffee <ArrowRight size={15} /></a></div></div></section>

      <footer className="flex flex-col gap-8 border-t border-white/10 px-5 py-8 md:flex-row md:items-center md:justify-between md:px-10 lg:px-20"><div className="font-mono text-xs text-[#69726c]">FED-EDU / <span className="text-[#b8f34a]">ALL BUILDERS WELCOME</span></div><div className="flex flex-wrap gap-5 font-mono text-[10px] text-[#69726c]"><a href="https://github.com" target="_blank" rel="noreferrer" className="hover:text-white">GitHub ↗</a><a href="https://ko-fi.com" target="_blank" rel="noreferrer" className="hover:text-white">Ko-fi ↗</a><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="hover:text-white">Back to top ↑</button></div></footer>
    </main>
  );
}
